<a href="https://colab.research.google.com/github/jsChaparroj/Ciencia_de_datos/blob/main/Taller1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import os as os
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt
import numpy as np

# Taller 1 

### 1.  Cargue la base de datos.

In [3]:
datos = pd.read_csv("/content/drive/MyDrive/V semestre/DataScience/Delitos_en_Colombia.csv")
datos.head()

,TEMÁTICA,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,HORA,BARRIO,ZONA,CLASE SITIO,ARMA EMPLEADA,MOVIL AGRESOR,MOVIL VICTIMA,EDAD,SEXO,ESTADO CIVIL,PAIS NACE,CLASE EMPLEADO,PROFESION,ESCOLARIDAD,CODIGO DANE
0,ABIGEATO,01/01/2014,MAGDALENA,ARIGUANÍ,Miércoles,4:00,VEREDA ANA MARIA,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,27,FEMENINO,SOLTERO,COLOMBIA,INDEPENDIENTE,NO REPORTADO,SUPERIOR,47058000.0
1,ABIGEATO,01/01/2014,META,MESETAS,Miércoles,18:00,VEREDA LAS ROSAS,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,46,MASCULINO,CASADO,COLOMBIA,AGRICULTOR,NO REPORTADO,SECUNDARIA,50330000.0
2,ABIGEATO,01/01/2014,META,PUERTO LÓPEZ,Miércoles,6:00,VEREDA SAN LUIS DE RIO NEGRO,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,62,MASCULINO,CASADO,NO REPORTADO,AGRICULTOR,NO REPORTADO,PRIMARIA,50573000.0
3,ABIGEATO,02/01/2014,ANTIOQUIA,ANDES,Jueves,1:00,QUEBRADA ARRIBA,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,NO REPORTADO,25,MASCULINO,CASADO,COLOMBIA,AGRICULTOR,NO REPORTADO,PRIMARIA,5034000.0
4,ABIGEATO,02/01/2014,BOYACÁ,CÓMBITA,Jueves,12:00,VDA. SAN ONOFRE,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,48,MASCULINO,CASADO,COLOMBIA,AGRICULTOR,NO REPORTADO,PRIMARIA,15204000.0

#### Analisis exploratorio

In [4]:
## Variables tipo categorico
datos1 = datos.select_dtypes("object")
unicos = datos1.apply(lambda x: x.unique())
print(unicos)

TEMÁTICA          [ABIGEATO, ABIGEATO,,TOLIMA,SAN ANTONIO,Jueves...
FECHA             [01/01/2014, 02/01/2014, 03/01/2014, 04/01/201...
DEPARTAMENTO      [MAGDALENA, META, ANTIOQUIA, BOYACÁ, TOLIMA, C...
MUNICIPIO         [ARIGUANÍ, MESETAS, PUERTO LÓPEZ, ANDES, CÓMBI...
DIA               [Miércoles, Jueves, Viernes, Sábado, Domingo, ...
HORA              [4:00, 18:00, 6:00, 1:00, 12:00, 15:30, 9:30, ...
BARRIO            [VEREDA ANA MARIA, VEREDA LAS ROSAS, VEREDA SA...
ZONA                                           [RURAL, URBANA, nan]
CLASE SITIO       [FINCAS Y SIMILARES, POTREROS, VIAS PUBLICAS, ...
ARMA EMPLEADA     [SIN EMPLEO DE ARMAS, ARMA BLANCA, ARMA DE FUE...
MOVIL AGRESOR     [A PIE, VEHICULO, NO REPORTADO, PASAJERO MOTOC...
MOVIL VICTIMA     [A PIE, NO REPORTADO, BICICLETA, VEHICULO, nan...
EDAD              [27, 46, 62, 25, 48, 45, 71, 32, 58, 39, 29, 3...
SEXO              [FEMENINO, MASCULINO, NO REPORTADO, nan, -, NO...
ESTADO CIVIL      [SOLTERO, CASADO, UNION LIBRE, VIUDO, DIVORCIA...
PAIS NACE         [COLOMBIA, NO REPORTADO, LIBANO, VENEZUELA, na...
CLASE EMPLEADO    [INDEPENDIENTE, AGRICULTOR, AMA DE CASA, COMER...
PROFESION         [NO REPORTADO, LICENCIADO, MEDICO, MATEMATICO,...
ESCOLARIDAD       [SUPERIOR, SECUNDARIA, PRIMARIA, TECNICO, ANAL...
dtype: object

In [5]:
nombres_var = unicos.index
for i in range(0,len(unicos)):  
  print("Variable:",nombres_var[i],"\n",unicos[i][0:30],"\n")

Variable: TEMÁTICA
 ['ABIGEATO'
 'ABIGEATO,,TOLIMA,SAN ANTONIO,Jueves,16:00,CENTRO,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,87,MASCULINO,SOLTERO,COLOMBIA,ETNIA INDIGENA,NO REPORTADO,SECUNDARIA,73675000'
 'ABIGEATO,,BOYACÁ,PAZ DE RÍO,Domingo,23:00,PARQUE PRINCIPAL,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,45,MASCULINO,SOLTERO,COLOMBIA,COMERCIANTE,NO REPORTADO,SECUNDARIA,15537000'
 'ABIGEATO,,MAGDALENA,PLATO,Miércoles,11:00,LOS GUAYACANES,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,25,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,NO REPORTADO,SECUNDARIA,47555000'
 'ABIGEATO,,ANTIOQUIA,BELLO,Miércoles,12:30:00,SAN JOSE OBRERO,URBANA,"FERRERERAS, MARRANERAS Y CABALLERIZAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,47,MASCULINO,CASADO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,5088000'
 'ABIGEATO,,CASANARE,VILLANUEVA,Lunes,7:00:00,AGUACLARA,RURAL,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,60,MASCULINO,CASADO,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,85440000'
 'ABIGEATO,02/04/2016,HUILA,NEIVA (CT),Sábado,10:00:00,EL TRIANGULO,URBANA,"FERRERERAS, MARRANERAS Y CABALLERIZAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,39,MASCULINO,UNION LIBRE,COLOMBIA,COMERCIANTE,-,SECUNDARIA,41001000'
 'ABIGEATO,,GUAJIRA,SAN JUAN DEL CESAR,Viernes,7:00:00,CORREGIMIENTO DE LA JUNTA,RURAL,"MATADEROS, CARNICERIA Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,50,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,44650000'
 'ABIGEATO,,TOLIMA,LÍBANO,Domingo,1:00:00,"SECTOR LA ""Y""",URBANA,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,51,FEMENINO,SOLTERO,COLOMBIA,COMERCIANTE,-,SECUNDARIA,73411000'
 'ABIGEATO,,BOLÍVAR,CICUCO,Viernes,0:00:00,SECTOR CENTRO,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",ARMA BLANCA / CORTOPUNZANTE,A PIE,A PIE,45,FEMENINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,13188000'
 'AMENAZA'
 'AMENAZA,02/01/2016,QUINDÍO,CALARCA,Sábado,20:00:00,VDA.PLANADAS,RURAL,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,57,MASCULINO,CASADO,-,EMPLEADO PARTICULAR,-,SECUNDARIA,63130000'
 'AMENAZA,03/01/2016,CAQUETÁ,SAN VICENTE DEL CAGUÁN,Domingo,2:00:00,HERNANDEZ,URBANA,"HOTELES, RESIDENCIAS, Y SIMILARES.",SIN EMPLEO DE ARMAS,A PIE,A PIE,21,MASCULINO,SOLTERO,COLOMBIA,INDEPENDIENTE,TECNICO EMPRESARIAL,TECNICO,18753000'
 'AMENAZA,08/01/2016,CÓRDOBA,TIERRALTA,Viernes,11:00:00,CENTRO,URBANA,"DROGUERIAS, FARMACIAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,47,FEMENINO,CASADO,COLOMBIA,INDEPENDIENTE,TECNICO EN SISTEMAS,TECNICO,23807000'
 'AMENAZA,08/01/2016,CUNDINAMARCA,BOGOTÁ D.C. (CT),Viernes,10:00:00,PARQUE NACIONAL E-3,URBANA,"HOTELES, RESIDENCIAS, Y SIMILARES.",SIN EMPLEO DE ARMAS,A PIE,A PIE,37,MASCULINO,CASADO,-,INDEPENDIENTE,ADMINISTRADOR DE EMPRESAS,SUPERIOR,11001000'
 'AMENAZA,08/01/2016,META,ACACÍAS,Viernes,5:30:00,CENTRO,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,50,FEMENINO,UNION LIBRE,COLOMBIA,INDEPENDIENTE,-,SECUNDARIA,50006000'
 'AMENAZA,12/01/2016,CÓRDOBA,AYAPEL,Martes,18:00:00,BOLIVAR,URBANA,"DROGUERIAS, FARMACIAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,30,FEMENINO,SOLTERO,COLOMBIA,INDEPENDIENTE,LICENCIADO,SUPERIOR,23068000'
 'AMENAZA,,CUNDINAMARCA,BOGOTÁ D.C. (CT),Viernes,12:40:00,"LA SOLEDAD, SAN JOSÉ NORTE E-10",URBANA,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,27,FEMENINO,UNION LIBRE,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,11001000'
 'AMENAZA,,CAQUETÁ,CARTAGENA DEL CHAIRÁ,Sábado,6:00:00,VDA.  SANTA FE,RURAL,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,28,FEMENINO,UNION LIBRE,COLOMBIA,EDUCADOR,MATEMATICO,SUPERIOR,18150000'
 'AMENAZA,,BOYACÁ,TUNJA (CT),Lunes,7:00:00,CENTRO,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,58,MASCULINO,CASADO,COLOMBIA,EMPLEADO PARTICULAR,-,TECNOLOGO,15001000'
 'AMENAZA,,CALDAS,ANSERMA,Lunes,11:00:00,BARRIO OBRERO,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,31,FEMENINO,SOLTERO,COLOMBIA,EDUCADOR,LICENCIADO,SUPERIOR,17042000'
 'AMENAZA,,CAUCA,CAJIBÍO,Lunes,10:00:00,CALLE REAL,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,42,FEMENINO,UNION LIBRE,COLOMBIA,EMPLEADO PUBLICO,LICENCIADO,SUPERIOR,19130000'
 'AMENAZA,,CUNDINAMARCA,BOGOTÁ D.C. (CT),Miércoles,10:00:00,"LA SOLEDAD, SAN JOSÉ NORTE E-10",URBANA,DENTRO DE LA VIVIENDA,SIN EMPLEO DE ARMAS,A PIE,A PIE,47,FEMENINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,11001000'
 'AMENAZA,,BOYACÁ,TUNJA (CT),Jueves,10:30:00,CENTRO,URBANA,"HOTELES, RESIDENCIAS, Y SIMILARES.",SIN EMPLEO DE ARMAS,A PIE,A PIE,22,FEMENINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,15001000'
 'AMENAZA,,ATLÁNTICO,BARRANQUILLA (CT),Lunes,10:25:00,SAN FRANCISCO,URBANA,"HOTELES, RESIDENCIAS, Y SIMILARES.",SIN EMPLEO DE ARMAS,A PIE,A PIE,43,FEMENINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,8001000'
 'AMENAZA,,BOYACÁ,SOGAMOSO,Jueves,0:00:00,LOS LIBERTADORES,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,44,FEMENINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,-,PRIMARIA,15759000'
 'AMENAZA,,CALDAS,LA MERCED,Viernes,16:00:00,PARQUE PRINCIPAL,URBANA,"BARES, CANTINAS Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,43,MASCULINO,CASADO,COLOMBIA,EMPLEADO PUBLICO,-,SUPERIOR,17388000'
 'AMENAZA,,SANTANDER,CIMITARRA,Sábado,23:00:00,VRDA SAN PEDRO DE LA PAZ,RURAL,"HOTELES, RESIDENCIAS, Y SIMILARES.",CONTUNDENTES,A PIE,A PIE,29,FEMENINO,SOLTERO,COLOMBIA,AMA DE CASA,-,SECUNDARIA,68190000'
 'AMENAZA,01/02/2016,HUILA,NEIVA (CT),Lunes,10:00:00,QUIRINAL,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,16,MASCULINO,SOLTERO,COLOMBIA,ESTUDIANTE,-,SECUNDARIA,41001000'
 'AMENAZA,03/02/2016,NARIÑO,LA CRUZ,Miércoles,10:00:00,CENTRO,URBANA,"COLEGIOS, ESCUELAS",SIN EMPLEO DE ARMAS,A PIE,A PIE,35,MASCULINO,SOLTERO,COLOMBIA,EMPLEADO PARTICULAR,TECNOLOGO SOLDADURA,TECNOLOGO,52378000']

Variable: FECHA
 ['01/01/2014' '02/01/2014' '03/01/2014' '04/01/2014' '05/01/2014'
 '06/01/2014' '07/01/2014' '08/01/2014' '09/01/2014' '10/01/2014'
 '11/01/2014' '12/01/2014' nan '01/02/2014' '02/02/2014' '03/02/2014'
 '04/02/2014' '05/02/2014' '06/02/2014' '07/02/2014' '08/02/2014'
 '09/02/2014' '10/02/2014' '11/02/2014' '12/02/2014' '01/03/2014'
 '02/03/2014' '03/03/2014' '04/03/2014' '05/03/2014']

Variable: DEPARTAMENTO
 ['MAGDALENA' 'META' 'ANTIOQUIA' 'BOYACÁ' 'TOLIMA' 'CÓRDOBA' 'HUILA'
 'NORTE DE SANTANDER' 'SANTANDER' 'VALLE' 'BOLÍVAR' 'CASANARE' 'ATLÁNTICO'
 'CAQUETÁ' 'QUINDÍO' 'ARAUCA' 'GUAJIRA' 'CESAR' 'RISARALDA' 'SUCRE'
 'CALDAS' 'CUNDINAMARCA' 'VICHADA' 'CAUCA' 'NARIÑO' 'PUTUMAYO' 'CHOCÓ' nan
 'AMAZONAS' 'GUAVIARE']

Variable: MUNICIPIO
 ['ARIGUANÍ' 'MESETAS' 'PUERTO LÓPEZ' 'ANDES' 'CÓMBITA' 'PIVIJAY' 'CUMARAL'
 'PURIFICACIÓN' 'LORICA' 'MONTERÍA (CT)' 'LA PLATA' 'OCAÑA' 'BARBOSA'
 'IBAGUÉ (CT)' 'LÍBANO' 'TULUÁ' 'MAHATES' 'NOBSA' 'SAN LUIS DE PALENQUE'
 'SAN CARLOS' 'MANATÍ' 'SAN VICENTE DEL CAGUÁN' 'PITAL' 'QUIMBAYA'
 'BARRANCABERMEJA' 'MEDELLÍN (CT)' 'ARAUCA (CT)' 'MORALES' 'CUÍTIVA'
 'SAHAGÚN']

Variable: DIA
 ['Miércoles' 'Jueves' 'Viernes' 'Sábado' 'Domingo' 'Lunes' 'Martes' nan]

Variable: HORA
 ['4:00' '18:00' '6:00' '1:00' '12:00' '15:30' '9:30' '9:15' '0:30' '0:00'
 '2:00' '5:00' '14:00' '13:00' '9:37' '23:45' '17:00' '9:00' '10:00'
 '18:40' '12:30' '6:30' '8:00' '14:30' '7:00' '5:30' '20:00' '21:00'
 '1:10' '11:00']

Variable: BARRIO
 ['VEREDA ANA MARIA' 'VEREDA LAS ROSAS' 'VEREDA SAN LUIS DE RIO NEGRO'
 'QUEBRADA ARRIBA' 'VDA. SAN ONOFRE' 'CORREGIMIENTO DE CARRETO'
 'VEREDA SAN ANTONIO' 'LA BATEA' 'VEREDA ALTO NAVAJAS' 'VRDA. LA MATA'
 'CGTO LOS CORRALES' 'SITIO EL QUINCE' 'VEREDA EL CABUYAL'
 'CORREGIMIENTO LA HERMITA' 'VRDA FRANCISCO DE PAULA SANTANDER'
 'JORDAN VIII ETAPA' 'VRDA. EL MIRADOR' 'Cgto Aguaclara' 'CORREG. EVITAR'
 'NAZARETH' 'INSP.PASO REAL DEL ALGARROBO' 'VEREDA LA COSTA' 'EL PORVENIR'
 'VDA. LA ARENOSA' 'VEREDA HATO VIEJO' 'CIUDADELA EL ENSUEÑO'
 'VIA BUCARAMANGA' 'OCHO DE MARZO  C-9' 'VEREDA MAPORAL'
 'VDA. BOCA LA HONDA']

Variable: ZONA
 ['RURAL' 'URBANA' nan]

Variable: CLASE SITIO
 ['FINCAS Y SIMILARES' 'POTREROS' 'VIAS PUBLICAS' 'TRAMO DE VIA'
 'CASAS DE HABITACION' 'FRENTE A RESIDENCIAS NO REPORTADO VIA PUBLICA'
 'CARRETERA' 'LOTE BALDIO' 'CABAÑA' 'HACIENDA' 'TROCHA' 'CANCHA DE FUTBOL'
 'RANCHERIA' 'FERIA GANADO' nan 'PLAZA DE TOROS' 'PARQUES' 'CORPORACIONES'
 'SECTOR COMERCIO' 'PERIMETRO URBANO' 'PARQUEADERO'
 'DENTRO DE LA VIVIENDA' 'ZONA SELVÁTICA' 'BODEGAS Y SIMILARES'
 'FRENTE CONJUNTO - VIA PUBLICA' 'CALLEJÓN' 'APARTAMENTO' 'UNIVERSIDADES'
 'PLAYA' 'BOSQUES']

Variable: ARMA EMPLEADA
 ['SIN EMPLEO DE ARMAS' 'ARMA BLANCA' 'ARMA DE FUEGO' 'NO REPORTADO' nan
 'ARMA BLANCA / CORTOPUNZANTE' '-' 'CONTUNDENTES' 'ESCOPOLAMINA'
 'GRANADA DE MANO' 'MOTO' 'POLVORA(FUEGOS PIROTECNICOS)' 'PUNZANTES'
 'ARTEFACTO EXPLOSIVO/CARGA DINAMITA' 'VEHICULO' 'PAPA EXPLOSIVA' 'PERRO'
 'QUIMICOS' 'MINA ANTIPERSONA' 'AGUA CALIENTE' 'ACIDO' 'GASOLINA'
 'SUSTANCIAS TOXICAS' 'JERINGA' 'CINTAS' 'PAQUETE BOMBA' 'CUCHILLA'
 'GASES' 'MEDICAMENTOS' 'CARRO BOMBA']

Variable: MOVIL AGRESOR
 ['A PIE' 'VEHICULO' 'NO REPORTADO' 'PASAJERO MOTOCICLETA'
 'CONDUCTOR MOTOCICLETA' 'BICICLETA' 'CONDUCTOR TAXI' nan
 'CONDUCTOR VEHICULO' '-' 'PASAJERO BUS' 'CONDUCTOR BUS' 'PASAJERO TAXI'
 'PASAJERO METRO' 'PASAJERO VEHICULO' 'TRIPULANTE AERONAVE'
 'PASAJERO BARCO' 'NO REPORTADA']

Variable: MOVIL VICTIMA
 ['A PIE' 'NO REPORTADO' 'BICICLETA' 'VEHICULO' nan 'CONDUCTOR TAXI' '-'
 'CONDUCTOR VEHICULO' 'PASAJERO MOTOCICLETA' 'CONDUCTOR MOTOCICLETA'
 'PASAJERO BUS' 'PASAJERO TAXI' 'CONDUCTOR BUS' 'PASAJERO METRO'
 'TRIPULANTE AERONAVE' 'PASAJERO VEHICULO' 'NO REPORTADA']

Variable: EDAD
 ['27' '46' '62' '25' '48' '45' '71' '32' '58' '39' '29' '33' '42' '43'
 '72' '40' '54' '47' '34' '23' '52' '60' '49' '57' '50' '80' '68' '73'
 '70' '35']

Variable: SEXO
 ['FEMENINO' 'MASCULINO' 'NO REPORTADO' nan '-' 'NO REPORTA' 'NO REPORTADA']

Variable: ESTADO CIVIL
 ['SOLTERO' 'CASADO' 'UNION LIBRE' 'VIUDO' 'DIVORCIADO' 'NO REPORTADO'
 'SEPARADO' nan '-' 'NO REPORTA' 'NO REPORTADA']

Variable: PAIS NACE
 ['COLOMBIA' 'NO REPORTADO' 'LIBANO' 'VENEZUELA' nan '-' 'CANADA'
 'INGLATERRA' 'ECUADOR' 'GRECIA' 'MARRUECOS' 'ALEMANIA' 'ESPAÑA' 'PERU'
 'NICARAGUA' 'ESTADOS UNIDOS' 'ARMENIA' 'TURQUIA' 'ISRAEL' 'ITALIA'
 'ARGENTINA' 'FRANCIA' 'AUSTRALIA' 'CHINA' 'SUECIA' 'SUIZA' 'RUSIA'
 'HOLANDA' 'CUBA' 'COREA']

Variable: CLASE EMPLEADO
 ['INDEPENDIENTE' 'AGRICULTOR' 'AMA DE CASA' 'COMERCIANTE'
 'EMPLEADO PARTICULAR' 'GANADERO' 'EMPLEADO POLICIAL' 'EMPLEADO PUBLICO'
 'DESEMPLEADO' 'PENSIONADO' 'EMPLEADO SALUD' 'CANDIDATOS' 'NO REPORTA'
 'EDUCADOR' 'ETNIA INDIGENA' 'ESTUDIANTE' 'NO REPORTADO' 'RELIGIOSO'
 'EMPLEADO ARMADA/MARINA' nan 'EMPLEADO EJERCITO' 'RAMA JUDICIAL'
 'SECTOR FINANCIERO' 'POLITICO' 'DELINCUENCIA' 'EMPLEADO INPEC'
 'LIDER CIVICO' 'SINDICALISTA' 'AFRODESCENDIENTE' '-']

Variable: PROFESION
 ['NO REPORTADO' 'LICENCIADO' 'MEDICO' 'MATEMATICO'
 'ADMINISTRADOR AGROPECUARIO' 'POLICIA' 'ZOOTECNICO' 'ARQUITECTO'
 'ADMINISTRADOR DE EMPRESAS' 'ODONTOLOGO' 'ABOGADO' 'TECNICO EN SISTEMAS'
 'ADMINISTRADOR AGROINDUSTRIAL' 'TECNICO EMPRESARIAL'
 'INGENIERO ELECTRICO' 'MEDICO VETERINARIO' 'ADMINISTRADOR EDUCATIVO'
 'TECNICO EN MERCADEO' 'INGENIERO' 'CONTADOR PUBLICO' 'AGRONOMO'
 'INGENIERO AGRONOMO' 'TECNICO EN CONTABILIDAD' nan
 'TECNOLOGO AGROPECUARIO' 'PILOTO' 'CONTADOR' 'INGENIERO CIVIL'
 'INGENIERO INDUSTRIAL' 'TECNICO ELECTRICISTA']

Variable: ESCOLARIDAD
 ['SUPERIOR' 'SECUNDARIA' 'PRIMARIA' 'TECNICO' 'ANALFABETA' 'NO REPORTADO'
 'TECNOLOGO' nan '-' 'NO REPORTADA']

Algunas variables presentan valores ausentes, las cuales están reportadas como: No reportado, no reporta, "-" entre otros.
Este problema se soluciona cambiando estos valores como nan

In [35]:
def limpiar_paraNa(x):
  if type(x) is str:
    if "NO " in x:
      x = np.nan
      return x
    else:
     if "-" in x:
       x = np.nan
       return x
  return x

In [36]:
datos  = datos.applymap(limpiar_paraNa)

In [37]:
datos["SEXO"].unique()

array(['FEMENINO', 'MASCULINO', nan], dtype=object)

También se observa que la variable "TEMÁTICA" está probablemente mal cargada, puesto que en esta está contenida toda la información restante de la data, dejando las demás variables ausentes.

In [41]:
datos[datos["TEMÁTICA"].str.contains(",")]

ValueError: ignored

### 2. Obtener una base de datos por municipios, que contenga la cantidad de delitos por tem´atica, porcentaje de mujeres victimas y porcentaje de delitos en zonas rural

In [13]:
filtro1 = datos[(datos["SEXO"] == "FEMENINO") & (datos["ZONA"] == "RURAL")]
filtro1.sample(5)

,TEMÁTICA,FECHA,DEPARTAMENTO,MUNICIPIO,DIA,HORA,BARRIO,ZONA,CLASE SITIO,ARMA EMPLEADA,MOVIL AGRESOR,MOVIL VICTIMA,EDAD,SEXO,ESTADO CIVIL,PAIS NACE,CLASE EMPLEADO,PROFESION,ESCOLARIDAD,CODIGO DANE
248834,HOMICIDIOS,15/03/2014,GUAJIRA,DISTRACCIÓN,Sábado,17:30,CORREGIMIENTO DE CHORRERAS,RURAL,TROCHA,ARMA BLANCA,A PIE,A PIE,14,FEMENINO,SOLTERO,COLOMBIA,ESTUDIANTE,NO REPORTADO,SECUNDARIA,44098000.0
537613,DELITOS SEXUALES,09/07/2016,BOYACÁ,PUERTO BOYACÁ,Sábado,15:00:00,VDA. EL MARFIL,RURAL,VIAS PUBLICAS,SIN EMPLEO DE ARMAS,A PIE,A PIE,5,FEMENINO,SOLTERO,COLOMBIA,DESEMPLEADO,-,ANALFABETA,15572000.0
557020,DELITOS SEXUALES,31/10/2015,ANTIOQUIA,YOLOMBÓ,Sábado,8:00,LA MARIA,RURAL,FINCAS Y SIMILARES,SIN EMPLEO DE ARMAS,A PIE,A PIE,14,FEMENINO,SOLTERO,COLOMBIA,ESTUDIANTE,NO REPORTADO,SECUNDARIA,5890000.0
154792,LESIONES PERSONALES,20/05/2016,RISARALDA,PEREIRA (CT),Viernes,13:00:00,CAIMALITO,RURAL,VIAS PUBLICAS,CONTUNDENTES,A PIE,A PIE,28,FEMENINO,UNION LIBRE,COLOMBIA,EMPLEADO PARTICULAR,-,SECUNDARIA,66001000.0
215961,VIOLENCIA INTRAFAMILIAR,28/04/2016,HUILA,NEIVA (CT),Jueves,8:00:00,VEREDA HORIZONTE,RURAL,CASAS DE HABITACION,CONTUNDENTES,A PIE,A PIE,22,FEMENINO,UNION LIBRE,COLOMBIA,AMA DE CASA,NO REPORTADO,SECUNDARIA,41001000.0

In [14]:
df1 = pd.pivot_table(filtro1,index = ["MUNICIPIO","TEMÁTICA"] ,values=["SEXO","ZONA"]  ,  aggfunc="count")
df1

                                       SEXO  ZONA
MUNICIPIO     TEMÁTICA
ABEJORRAL     DELITOS SEXUALES            5     5
              LESIONES PERSONALES         1     1
              VIOLENCIA INTRAFAMILIAR     1     1
ABREGO        ABIGEATO                    1     1
              AMENAZA                     4     4
...                                     ...   ...
ZONA BANANERA DELITOS SEXUALES           10    10
              HOMICIDIOS                  4     4
              LESIONES PERSONALES        13    13
              VIOLENCIA INTRAFAMILIAR     7     7
ÚTICA         HOMICIDIOS                  1     1

[4570 rows x 2 columns]

In [15]:
datos["TEMÁTICA"].unique()

array(['ABIGEATO',
       'ABIGEATO,,TOLIMA,SAN ANTONIO,Jueves,16:00,CENTRO,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,87,MASCULINO,SOLTERO,COLOMBIA,ETNIA INDIGENA,NO REPORTADO,SECUNDARIA,73675000',
       'ABIGEATO,,BOYACÁ,PAZ DE RÍO,Domingo,23:00,PARQUE PRINCIPAL,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",SIN EMPLEO DE ARMAS,A PIE,A PIE,45,MASCULINO,SOLTERO,COLOMBIA,COMERCIANTE,NO REPORTADO,SECUNDARIA,15537000',
       ...,
       'EXTORCIÓN,05/01/2014,META,VILLAVICENCIO (CT),Domingo,9:45,MAIZARO,URBANA,"HOTELES, RESIDENCIAS, Y SIMILARES.",LLAMADA TELEFONICA,A PIE,A PIE,NO REPORTADA,NO REPORTADA,NO REPORTADA,NO REPORTADA,NO REPORTADA,NO REPORTADA,NO REPORTADA,50001000',
       'EXTORCIÓN,02/01/2014,VALLE,CALI (CT),Jueves,8:30,MOJICA E15,URBANA,"MATADEROS, CARNICERIA Y SIMILARES",MIXTA,A PIE,A PIE,46,MASCULINO,DIVORCIADO,COLOMBIA,COMERCIANTE,NO REPORTADA,SECUNDARIA,76001000',
       'EXTORCIÓN,02/01/2014,MAGDALENA,SANTA MARTA (CT),Jueves,12:00,MAMATOCO,URBANA,"HOTELES, RESIDENCIAS, Y SIMILARES.",DIRECTA,A PIE,A PIE,53,MASCULINO,CASADO,COLOMBIA,EMPLEADO PARTICULAR,TECNOLOGO SOLDADURA,TECNOLOGO,47001000'],
      dtype=object)